### PR TITLE
Filter

### PR DESCRIPTION
**Pull request by sedv8808**
Hi @SimonGoring 

I am sorry, I think this PR contains a lot of information:
- Offset fixed
- `get_sites` function with tests/checks
- `get_datasets` function with tests/checks
- `get_downloads` function with tests/checks

I might still need to fix the tables regarding the downloads object but I think it can start to be used.

I would appreciate to have it reviewed and implemented so that I can start off a clean branch focusing mostly on download_objects and vignettes. 

I would also like to create a new branch to focus on creating new objects: `set_sites()`, `set_datasets()`, `set_downloads()`

The API for downloads is not accepting a list of datasetIDs  but once the API is fixed, the code should be able to run.

### CODE REVIEW

**Comment by SimonGoring** [comment]
Can you please remove the:

```r
[1] "let's check errors"
```

message, and have that only pop up as a warning/error if there are issues?

**Comment by SimonGoring** [comment]
Line 183 of the Vignette:
```r
> filter(brazil_datasets, datasettype == "geochronologic")
Error in storage.mode(x) <- "double" : 
  no method for coercing this S4 class to a vector
```
I'll take a look to see why this is an issue. . .

**Comment by sedv8808** [comment]
> Can you please remove the:
> 
> ```r
> [1] "let's check errors"
> ```
> 
> message, and have that only pop up as a warning/error if there are issues?

Hi Simon,

Could you let me know when is this message appearing to you? I deleted this message in previous commits. 

I verified the code and make sure it is not there any more. also changed one condition for messages being printed in the return statements.

I hope this should suffice :) 

Thank you,

Socorro

**Comment by SimonGoring** [comment]
This may have been an issue with the build/install process.  I'll check again.

**Pull request merged**
